//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input System/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""7461136e-a03b-4624-b68c-76c0146f6d7c"",
            ""actions"": [
                {
                    ""name"": ""MoveAndAim"",
                    ""type"": ""Value"",
                    ""id"": ""bce2cfd5-0189-47eb-b321-b8e58822fef2"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""d0028c6e-5ed8-4121-9db9-2d39b6c8fcda"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Parachute"",
                    ""type"": ""Button"",
                    ""id"": ""b51101f8-bcde-43bf-a872-870411dc6340"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeSpecialItem"",
                    ""type"": ""Value"",
                    ""id"": ""6facd9bd-8bf1-47c7-811f-f5f33c9273e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TimeBombMovement"",
                    ""type"": ""Button"",
                    ""id"": ""fcbfdd7b-f7ce-40ee-9a4d-bf469386fa2b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fire1"",
                    ""type"": ""Value"",
                    ""id"": ""26902dcd-2ac0-4c77-ac63-21d2e4c18cbe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fire2"",
                    ""type"": ""Button"",
                    ""id"": ""ca781ac6-61c2-4f7e-9564-b4ee45a60eef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fire3Special"",
                    ""type"": ""Button"",
                    ""id"": ""82eed940-98df-4c06-b006-f98c5eee2d16"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseMenu"",
                    ""type"": ""Button"",
                    ""id"": ""9b14817d-47ff-4ba8-ba2a-66b38a6ff1dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""aa92b8b9-485e-4d5e-9969-d04f2b7d88cc"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ebffc62-cec2-4ad6-bbf5-e7c14e3fffd4"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad RL"",
                    ""id"": ""c9c6b616-96ca-431b-bb45-51fc1438be03"",
                    ""path"": ""1DAxis(whichSideWins=1)"",
                    ""interactions"": """",
                    ""processors"": ""Normalize(min=-1,max=1),Scale"",
                    ""groups"": """",
                    ""action"": ""ChangeSpecialItem"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""177a4fb7-ed56-4675-a99b-a3ee5c4631b9"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeSpecialItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""50e978a7-03e3-43e1-80ad-eaeac69b7f12"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeSpecialItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""a8490052-66da-4db8-a316-30fd255010ae"",
                    ""path"": ""1DAxis(whichSideWins=1)"",
                    ""interactions"": """",
                    ""processors"": ""Normalize(min=-1,max=1),Scale"",
                    ""groups"": """",
                    ""action"": ""ChangeSpecialItem"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""2d5a6264-4673-4e41-8d63-4728bc6a225d"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeSpecialItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f4aa60ce-b467-4db1-bd89-ae57e923b55c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeSpecialItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""ec11ffa6-4f51-41b8-8198-314ebb05a1a6"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TimeBombMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""ef40eca7-1053-440e-9725-bc58d5bdf81f"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TimeBombMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""8f3247e4-29df-4741-b91a-f704fccf1531"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TimeBombMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""D Pad"",
                    ""id"": ""99fa2ced-b246-4e09-839e-36b495a8ea7c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveAndAim"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e31fe8cd-13d2-4d65-aa34-c7e4115e5a96"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveAndAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4c79bc99-d39f-4610-b5d3-800df746d1bf"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveAndAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c06c9e65-18f6-481a-be3c-4a55175688f3"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveAndAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f067712e-b6cc-4bd4-86c6-585b2d1783e1"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveAndAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""df6b32c9-e3d7-4dd2-ac67-a71add953575"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveAndAim"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""70daf97d-acdd-4a16-9444-d4cc0bb08c0b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveAndAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""33aebc7a-6683-4c0c-97b4-15c9657097d2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveAndAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""159a2c8a-382c-488c-9ce8-89411b70dbc2"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveAndAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""90c51b14-1da5-4401-98a8-723e885119b2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveAndAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1dd5d6f1-a3a7-4e14-8fe1-6a2716284d6f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Parachute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d60f617a-3786-431b-bcd0-e9e174b1e8ce"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Parachute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3734d4b6-837e-4a6e-9d6d-46f1b60c9049"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc3c3b4b-5452-4c9c-bec2-bd78cc5c929c"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a01a853-aee5-4d48-98f4-15ffb3e9ca91"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""121743c4-892d-4e9a-927e-fa404ab0ce96"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc3959a2-3024-4d55-94b0-8afabf7a0929"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire3Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85b8882f-ccfb-4b5c-b985-aa2080d52a20"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire3Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2fa45657-cd3b-44f2-bc7b-3dfee8684e79"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1a1fef2-ac70-4768-b0ee-6434ca04ddfa"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerSelectionMenu"",
            ""id"": ""881f3af6-755a-470e-9e1f-a27002ba1e89"",
            ""actions"": [
                {
                    ""name"": ""CursorNavigation"",
                    ""type"": ""Button"",
                    ""id"": ""94da86c2-3ffd-4f8c-97c4-e868fb7c4051"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectPlayer"",
                    ""type"": ""Button"",
                    ""id"": ""3f154ba5-69b4-488d-9b41-37654152bdfb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""D Pad"",
                    ""id"": ""7401294f-3e65-4ae1-bcd6-f16370c2160f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorNavigation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e00a5e7b-41cd-4fdd-88a5-10b65eca23de"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a39ebdcc-4e26-4c91-8452-56e0b7a29d22"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c34b1fdc-6834-4941-b563-72b55b937dfc"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""59a7f653-97bc-4e60-9a44-c1969b3e7858"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""8b5b4e41-4ac8-4b21-ac35-64ea8dca7c7e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorNavigation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2110c0a0-c69b-4b02-9f64-2757da2c9f06"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9a169a51-e7d6-4c93-8243-46a7902bb3b9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b3e2f09d-63ef-4e6d-b354-0667ce0bd250"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6042eeae-86c3-4ef1-9ffe-b52b65a3c530"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ea75ff62-278a-45e6-b206-29a0cb3653aa"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectPlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b192245e-b0e5-4b0c-9814-b0c0795380aa"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectPlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_MoveAndAim = m_Player.FindAction("MoveAndAim", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Parachute = m_Player.FindAction("Parachute", throwIfNotFound: true);
        m_Player_ChangeSpecialItem = m_Player.FindAction("ChangeSpecialItem", throwIfNotFound: true);
        m_Player_TimeBombMovement = m_Player.FindAction("TimeBombMovement", throwIfNotFound: true);
        m_Player_Fire1 = m_Player.FindAction("Fire1", throwIfNotFound: true);
        m_Player_Fire2 = m_Player.FindAction("Fire2", throwIfNotFound: true);
        m_Player_Fire3Special = m_Player.FindAction("Fire3Special", throwIfNotFound: true);
        m_Player_PauseMenu = m_Player.FindAction("PauseMenu", throwIfNotFound: true);
        // PlayerSelectionMenu
        m_PlayerSelectionMenu = asset.FindActionMap("PlayerSelectionMenu", throwIfNotFound: true);
        m_PlayerSelectionMenu_CursorNavigation = m_PlayerSelectionMenu.FindAction("CursorNavigation", throwIfNotFound: true);
        m_PlayerSelectionMenu_SelectPlayer = m_PlayerSelectionMenu.FindAction("SelectPlayer", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_MoveAndAim;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Parachute;
    private readonly InputAction m_Player_ChangeSpecialItem;
    private readonly InputAction m_Player_TimeBombMovement;
    private readonly InputAction m_Player_Fire1;
    private readonly InputAction m_Player_Fire2;
    private readonly InputAction m_Player_Fire3Special;
    private readonly InputAction m_Player_PauseMenu;
    public struct PlayerActions
    {
        private @PlayerInput m_Wrapper;
        public PlayerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveAndAim => m_Wrapper.m_Player_MoveAndAim;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Parachute => m_Wrapper.m_Player_Parachute;
        public InputAction @ChangeSpecialItem => m_Wrapper.m_Player_ChangeSpecialItem;
        public InputAction @TimeBombMovement => m_Wrapper.m_Player_TimeBombMovement;
        public InputAction @Fire1 => m_Wrapper.m_Player_Fire1;
        public InputAction @Fire2 => m_Wrapper.m_Player_Fire2;
        public InputAction @Fire3Special => m_Wrapper.m_Player_Fire3Special;
        public InputAction @PauseMenu => m_Wrapper.m_Player_PauseMenu;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @MoveAndAim.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoveAndAim;
                @MoveAndAim.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoveAndAim;
                @MoveAndAim.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoveAndAim;
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Parachute.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParachute;
                @Parachute.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParachute;
                @Parachute.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnParachute;
                @ChangeSpecialItem.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangeSpecialItem;
                @ChangeSpecialItem.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangeSpecialItem;
                @ChangeSpecialItem.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangeSpecialItem;
                @TimeBombMovement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTimeBombMovement;
                @TimeBombMovement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTimeBombMovement;
                @TimeBombMovement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTimeBombMovement;
                @Fire1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire1;
                @Fire1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire1;
                @Fire1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire1;
                @Fire2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire2;
                @Fire2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire2;
                @Fire2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire2;
                @Fire3Special.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire3Special;
                @Fire3Special.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire3Special;
                @Fire3Special.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire3Special;
                @PauseMenu.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPauseMenu;
                @PauseMenu.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPauseMenu;
                @PauseMenu.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPauseMenu;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MoveAndAim.started += instance.OnMoveAndAim;
                @MoveAndAim.performed += instance.OnMoveAndAim;
                @MoveAndAim.canceled += instance.OnMoveAndAim;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Parachute.started += instance.OnParachute;
                @Parachute.performed += instance.OnParachute;
                @Parachute.canceled += instance.OnParachute;
                @ChangeSpecialItem.started += instance.OnChangeSpecialItem;
                @ChangeSpecialItem.performed += instance.OnChangeSpecialItem;
                @ChangeSpecialItem.canceled += instance.OnChangeSpecialItem;
                @TimeBombMovement.started += instance.OnTimeBombMovement;
                @TimeBombMovement.performed += instance.OnTimeBombMovement;
                @TimeBombMovement.canceled += instance.OnTimeBombMovement;
                @Fire1.started += instance.OnFire1;
                @Fire1.performed += instance.OnFire1;
                @Fire1.canceled += instance.OnFire1;
                @Fire2.started += instance.OnFire2;
                @Fire2.performed += instance.OnFire2;
                @Fire2.canceled += instance.OnFire2;
                @Fire3Special.started += instance.OnFire3Special;
                @Fire3Special.performed += instance.OnFire3Special;
                @Fire3Special.canceled += instance.OnFire3Special;
                @PauseMenu.started += instance.OnPauseMenu;
                @PauseMenu.performed += instance.OnPauseMenu;
                @PauseMenu.canceled += instance.OnPauseMenu;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // PlayerSelectionMenu
    private readonly InputActionMap m_PlayerSelectionMenu;
    private IPlayerSelectionMenuActions m_PlayerSelectionMenuActionsCallbackInterface;
    private readonly InputAction m_PlayerSelectionMenu_CursorNavigation;
    private readonly InputAction m_PlayerSelectionMenu_SelectPlayer;
    public struct PlayerSelectionMenuActions
    {
        private @PlayerInput m_Wrapper;
        public PlayerSelectionMenuActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @CursorNavigation => m_Wrapper.m_PlayerSelectionMenu_CursorNavigation;
        public InputAction @SelectPlayer => m_Wrapper.m_PlayerSelectionMenu_SelectPlayer;
        public InputActionMap Get() { return m_Wrapper.m_PlayerSelectionMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerSelectionMenuActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerSelectionMenuActions instance)
        {
            if (m_Wrapper.m_PlayerSelectionMenuActionsCallbackInterface != null)
            {
                @CursorNavigation.started -= m_Wrapper.m_PlayerSelectionMenuActionsCallbackInterface.OnCursorNavigation;
                @CursorNavigation.performed -= m_Wrapper.m_PlayerSelectionMenuActionsCallbackInterface.OnCursorNavigation;
                @CursorNavigation.canceled -= m_Wrapper.m_PlayerSelectionMenuActionsCallbackInterface.OnCursorNavigation;
                @SelectPlayer.started -= m_Wrapper.m_PlayerSelectionMenuActionsCallbackInterface.OnSelectPlayer;
                @SelectPlayer.performed -= m_Wrapper.m_PlayerSelectionMenuActionsCallbackInterface.OnSelectPlayer;
                @SelectPlayer.canceled -= m_Wrapper.m_PlayerSelectionMenuActionsCallbackInterface.OnSelectPlayer;
            }
            m_Wrapper.m_PlayerSelectionMenuActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CursorNavigation.started += instance.OnCursorNavigation;
                @CursorNavigation.performed += instance.OnCursorNavigation;
                @CursorNavigation.canceled += instance.OnCursorNavigation;
                @SelectPlayer.started += instance.OnSelectPlayer;
                @SelectPlayer.performed += instance.OnSelectPlayer;
                @SelectPlayer.canceled += instance.OnSelectPlayer;
            }
        }
    }
    public PlayerSelectionMenuActions @PlayerSelectionMenu => new PlayerSelectionMenuActions(this);
    public interface IPlayerActions
    {
        void OnMoveAndAim(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnParachute(InputAction.CallbackContext context);
        void OnChangeSpecialItem(InputAction.CallbackContext context);
        void OnTimeBombMovement(InputAction.CallbackContext context);
        void OnFire1(InputAction.CallbackContext context);
        void OnFire2(InputAction.CallbackContext context);
        void OnFire3Special(InputAction.CallbackContext context);
        void OnPauseMenu(InputAction.CallbackContext context);
    }
    public interface IPlayerSelectionMenuActions
    {
        void OnCursorNavigation(InputAction.CallbackContext context);
        void OnSelectPlayer(InputAction.CallbackContext context);
    }
}
